-- MySQL Script generated by MySQL Workbench
-- Sat 17 Apr 2021 07:02:53 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CLIENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CLIENTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COUNTRIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COUNTRIES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COUNTRIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CITIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CITIES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CITIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  `zip_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cities_Country1_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cities_Country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`COUNTRIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCATIONS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LOCATIONS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LOCATIONS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Location_Cities1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_Location_Cities1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`CITIES` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROJECTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PROJECTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PROJECTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `begin_date` DATETIME NOT NULL,
  `location_id` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `expected_end_date` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Project_Location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`LOCATIONS` (`id`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASSETS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ASSETS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ASSETS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `weekly_hours` TIME NOT NULL,
  `project_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Assets_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_Assets_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`PROJECTS` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPLOYEES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EMPLOYEES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EMPLOYEES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asset_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `salary` DOUBLE NOT NULL,
  INDEX `fk_Employees_Assets1_idx` (`asset_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Employees_Assets1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `mydb`.`ASSETS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MACHINE_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MACHINE_TYPES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MACHINE_TYPES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPANIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`COMPANIES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`COMPANIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MACHINES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MACHINES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MACHINES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `asset_id` INT NOT NULL,
  `buying_date` DATETIME NOT NULL,
  `number` DOUBLE NOT NULL,
  `type_id` INT NOT NULL,
  `company_id` INT NOT NULL,
  INDEX `fk_Machines_Type1_idx` (`type_id` ASC) VISIBLE,
  INDEX `fk_Machines_Assets1_idx` (`asset_id` ASC) VISIBLE,
  INDEX `fk_Machines_Company1_idx` (`company_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Machines_Type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `mydb`.`MACHINE_TYPES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Machines_Assets1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `mydb`.`ASSETS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Machines_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `mydb`.`COMPANIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUPPLIERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SUPPLIERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SUPPLIERS` (
  `idSupliers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `location_id` INT NOT NULL,
  PRIMARY KEY (`idSupliers`),
  INDEX `fk_Supliers_Location1_idx` (`location_id` ASC) VISIBLE,
  CONSTRAINT `fk_Supliers_Location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `mydb`.`LOCATIONS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CONTRACTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CONTRACTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CONTRACTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `project_id` INT NOT NULL,
  `client_id` INT NOT NULL,
  `begin_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `prize` DOUBLE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Project_has_Clients_Clients1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_Project_has_Clients_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_Project_has_Clients_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`PROJECTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_has_Clients_Clients1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`CLIENTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAYMENTS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PAYMENTS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PAYMENTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `amount` DOUBLE NOT NULL,
  `serial_number` VARCHAR(45) NOT NULL,
  `contract_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Payments_Project_has_Clients1_idx` (`contract_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payments_Project_has_Clients1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `mydb`.`CONTRACTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MATERIALS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`MATERIALS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`MATERIALS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUPPLY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`SUPPLY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`SUPPLY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `material_id` INT NOT NULL,
  `supplier_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Materials_has_Supliers_Supliers1_idx` (`supplier_id` ASC) VISIBLE,
  INDEX `fk_Materials_has_Supliers_Materials1_idx` (`material_id` ASC) VISIBLE,
  CONSTRAINT `fk_Materials_has_Supliers_Materials1`
    FOREIGN KEY (`material_id`)
    REFERENCES `mydb`.`MATERIALS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materials_has_Supliers_Supliers1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`SUPPLIERS` (`idSupliers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WORK_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WORK_HISTORY` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WORK_HISTORY` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `beginDate` DATETIME NOT NULL,
  `endDate` DATETIME NULL,
  `asset_id` INT NOT NULL,
  `project_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Work_history_Assets1_idx` (`asset_id` ASC) VISIBLE,
  INDEX `fk_Work_history_Project1_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `fk_Work_history_Assets1`
    FOREIGN KEY (`asset_id`)
    REFERENCES `mydb`.`ASSETS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Work_history_Project1`
    FOREIGN KEY (`project_id`)
    REFERENCES `mydb`.`PROJECTS` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DRIVERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DRIVERS` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DRIVERS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `employee_id` INT NOT NULL,
  `license_id` VARCHAR(45) NOT NULL,
  INDEX `fk_Drivers_Employees1_idx` (`employee_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Drivers_Employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`EMPLOYEES` (`asset_id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LICENSES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`LICENSES` ;

CREATE TABLE IF NOT EXISTS `mydb`.`LICENSES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `exp_date` DATETIME NOT NULL,
  `driver_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Licenses_Drivers1_idx` (`driver_id` ASC) VISIBLE,
  CONSTRAINT `fk_Licenses_Drivers1`
    FOREIGN KEY (`driver_id`)
    REFERENCES `mydb`.`DRIVERS` (`employee_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
